p-x9/MachOKit

Sources/MachOKit/MachOImage+Symbols.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Model/Symbol/Nlist.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
A re-implementation of the `dladdr` function, like
=> Add function to find the closest symbol to a given address

Sources/MachOKit/MachOFile+ExportTrieEntries.swift, Sources/MachOKit/MachOFile+FunctionStarts.swift, Sources/MachOKit/MachOFile.swift, Sources/MachOKit/MachOImage+FunctionStarts.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Model/FunctionStart.swift, Sources/MachOKit/Protocol/LoadCommandsProtocol.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
=> Function Starts Iterator

Sources/MachOKit/MachOFile.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Model/DataInCodeEntry.swift, Sources/MachOKit/Protocol/LoadCommandsProtocol.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
=> Data In Code

Sources/MachOKit/LoadCommand/Model/Section.swift, Sources/MachOKit/Model/Relocation/Relocation.swift, Sources/MachOKit/Model/Relocation/RelocationInfo.swift, Sources/MachOKit/Model/Relocation/RelocationLength.swift, Sources/MachOKit/Model/Relocation/RelocationType.swift, Sources/MachOKit/Model/Relocation/ScatteredRelocationInfo.swift, Tests/MachOKitTests/MachOFilePrintTests.swift
=> Section Relocation Info

Sources/MachOKit/LoadCommand/Model/Section.swift, Sources/MachOKit/MachOFile.swift
This reverts commit f6fc7100b39f960ea8a7e3ac4586f4e0054f4c59.
=> Revert "fix offset of string table start"

Sources/MachOKit/DyldCache+SubCaches.swift, Sources/MachOKit/DyldCache.swift, Sources/MachOKit/Extension/String+.swift, Sources/MachOKit/Header/CPU.swift, Sources/MachOKit/Header/CPUType.swift, Sources/MachOKit/Header/DyldCacheHeader/DyldCacheHeader.swift, Sources/MachOKit/Header/DyldCacheHeader/DyldCacheType.swift, Sources/MachOKit/Header/MachHeader/MachHeader.swift, Sources/MachOKit/MachOFile+BindOperations.swift, Sources/MachOKit/MachOFile+ExportTrieEntries.swift, Sources/MachOKit/MachOFile+FunctionStarts.swift, Sources/MachOKit/MachOFile+RebaseOperations.swift, Sources/MachOKit/MachOFile+Strings.swift, Sources/MachOKit/MachOFile+Symbols.swift, Sources/MachOKit/MachOFile.swift, Sources/MachOKit/Model/DyldCache/DyldCacheImageInfo.swift, Sources/MachOKit/Model/DyldCache/DyldCacheImageTextInfo.swift, Sources/MachOKit/Model/DyldCache/DyldCacheLocalSymbolsEntry.swift, Sources/MachOKit/Model/DyldCache/DyldCacheLocalSymbolsInfo.swift, Sources/MachOKit/Model/DyldCache/DyldCacheMappingAndSlideInfo.swift, Sources/MachOKit/Model/DyldCache/DyldCacheMappingFlags.swift, Sources/MachOKit/Model/DyldCache/DyldCacheMappingInfo.swift, Sources/MachOKit/Model/DyldCache/DyldSubCacheEntry.swift, Sources/MachOKit/Protocol/DyldCacheLocalSymbolsEntryProtocol.swift, Sources/MachOKit/Util/exported.swift, Sources/MachOKitC/include/dyld_cache_format.h, Tests/MachOKitTests/DyldCachePrintTests.swift
=> Dyld cache

Sources/MachOKit/MachOFile.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Model/BindingSymbol.swift, Sources/MachOKit/Model/DependedDylib.swift, Sources/MachOKit/Protocol/LoadCommandsProtocol.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Tests/MachOKitTests/DyldCachePrintTests.swift, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
=> Improve dependencies

Sources/MachOKit/LoadCommand/SegmentCommand.swift, Sources/MachOKit/MachOImage+static.swift, Sources/MachOKit/MachOImage.swift, Tests/MachOKitTests/MachOPrintTests.swift
```swift
let f: @convention(c) (Int) -> String = { "\($0)" }
var ptr = unsafeBitCast(f, to: UnsafeRawPointer.self)
ptr = ptr.advanced(by: 1) // random offset
guard let (machO, symbol) = MachOImage.closestSymbol(at: ptr) else {
return
}
if let path = machO.path {
print(path)
}
print(symbol.demangledName)
```
=> Function for search symbol from all images

Sources/MachOKit/MachOImage+static.swift
- First, find the image with the closest address range
- return as lazy sequence
=> Improve symbol search

Sources/MachOKit/MachOImage.swift
=> Fix `vmaddrSlide` to calculate by myself

Sources/MachOKit/Util/exported.swift, scripts/generate-symbols.sh
https://forums.swift.org/t/docc-for-objective-c-static-library/60588/15
=> Fix not to omit MachOKit symbols to docc

Sources/MachOKit/LoadCommand/LoadCommand.swift
- Modified type of info accessor to `any LoadCommandWrapper` from `Any`
=> Improved accessor for loadcommand info

Sources/MachOKit/MachOFile+Symbols.swift, Sources/MachOKit/MachOImage+Symbols.swift, Sources/MachOKit/Model/DyldCache/DyldCacheLocalSymbolsInfo.swift, Sources/MachOKit/Protocol/MachORepresentable.swift
=> Conform `Symbols` Sequence to `RandomAccessCollection`

Sources/MachOKit/Extension/FileHandle+.swift
- layout size check
- loaded data size check
=> Add preconditions for reading data sequence

Sources/MachOKit/MachOFile+DyldChainedFixups.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerContent.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerFormat.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerInfo.swift, Sources/MachOKitC/include/chained_fixups.h
https://github.com/apple-oss-distributions/xnu/blob/94d3b452840153a99b38a3a9659680b2a006908e/EXTERNAL_HEADERS/mach-o/fixup-chains.h#L104
=> Support new pointer format `DYLD_CHAINED_PTR_ARM64E_SHARED_CACHE`

Sources/MachOKit/Extension/FileHandle+.swift, Sources/MachOKit/Extension/UnsafePointer+.swift, Sources/MachOKit/Util/Sequence/DataSequence.swift, Sources/MachOKit/Util/Sequence/MemorySequence.swift
```swift
@_spi(Support) import MachOKit
```
=> Expose support functions with @_spi.

Sources/MachOKit/Extension/dyld_chained_ptr+.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerContent.swift
- dyld_chained_ptr_arm64e_bind24
- dyld_chained_ptr_arm64e_auth_bind24
- dyld_chained_ptr_arm64e_shared_cache_rebase
- dyld_chained_ptr_arm64e_shared_cache_auth_rebase
=> Add description of additional dyld chainded ptr

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/Model/DyldCache/SwiftOptimization.swift, Sources/MachOKitC/include/swift.h, Tests/MachOKitTests/DyldCachePrintTests.swift
=> Swift optimization infos in dyld_shared_cache

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/Extension/Sequence+.swift, Sources/MachOKit/Model/DyldCache/DylibIndex.swift, Sources/MachOKit/Model/DyldCache/DylibsTrieNodeContent.swift, Tests/MachOKitTests/DyldCachePrintTests.swift
=> Support Dylibs Trie in dyld cache

Sources/MachOKit/DyldCache.swift, Tests/MachOKitTests/DyldCachePrintTests.swift
=> Support for code signatures in dyld cache

scripts/xcframework.sh
=> Support for building xcframework for MacCatalyst

Sources/MachOKit/Model/DyldCache/DyldCacheMappingAndSlideInfo.swift, Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo.swift, Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo1.swift, Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo2.swift, Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo3.swift, Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo4.swift, Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo5.swift, Tests/MachOKitTests/DyldCachePrintTests.swift
=> Dyld Cache Slide Info

Sources/MachOKit/Extension/String+.swift, Sources/MachOKit/Util/TrieTree/DataTrieTree.swift, Sources/MachOKit/Util/TrieTree/MemoryTrieTree.swift, Sources/MachOKit/Util/TrieTree/Model/TrieNode.swift
- String extension
- Trie Tree
=> Extend `Support` spi

Sources/MachOKit/Protocol/LayoutWrapper.swift
```swift
@_spi(Support) import MachOKit
```
=> Add some functions of `LayoutWrapper` to spi `Support`

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/MachOFile.swift
=> Resolve optional rebase in dyld shared cache or mach-o file

.github/workflows/release.yml
https://github.com/actions/runner-images/issues/10559
=> Install visionOS platform before build on GitHub Action

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/DyldCacheLoaded.swift, Sources/MachOKit/Header/DyldCacheHeader/DyldCacheHeader.swift
=> [dyld cache] Consider the actual size of dyld cache header

Sources/MachOKit/Model/DyldCache/DyldCacheMappingFlags.swift, Sources/MachOKitC/include/dyld_cache_format.h
https://github.com/apple-oss-distributions/dyld/blob/65bbeed63cec73f313b1d636e63f243964725a9d/cache-builder/dyld_cache_format.h
=> Update dyld cache format  (dyld-1231.3)

Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderInfoRO.swift, Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderOptimizationRO.swift, Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderOptimizationRW.swift, Tests/MachOKitTests/DyldCacheLoadedPrintTests.swift, Tests/MachOKitTests/DyldCachePrintTests.swift
```swift
guard let objcOptimization = cache.oldObjcOptimization else { return }
let ro = objcOptimization.headerOptimizationRO64(in: cache)!
let headerInfo = ro.headerInfo(in: cache, for: machO)
```
=> Add method to get objc ro optimization info of specified mach-o

Sources/MachOKit/LoadCommand/LoadCommand.swift, Sources/MachOKit/LoadCommand/NoteCommand.swift
=> Implemented `NoteCommand`

.github/workflows/release.yml, scripts/xcframework.sh
```
MachOKit.build/Objects-normal/arm64/MachOKit.private.swiftinterface:7:19: error: no such module 'MachOKitC'
@_exported import MachOKitC
```
=> Fix release process on Xcode16

Sources/MachOKit/DyldCacheLoaded+static.swift, Sources/MachOKit/MachOImage+static.swift
- https://developer.apple.com/documentation/swift/dsohandle()
```swift
let machO = MachOImage.current()
let machOExecutable = MachOImage.currentExecutable
let cache = DyldCacheLoaded.current
```
=> Add property to get current MachOImage/DyldCacheLoaded instance

.github/workflows/ci.yml
=> Use Ubuntu 22.04 in CI

.github/workflows/docc.yml, .github/workflows/release.yml
=> Deploy latest documentation at release time

Sources/MachOKit/DyldCacheLoaded.swift, Sources/MachOKit/LoadCommand/Model/Section.swift, Sources/MachOKit/MachOFile.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Model/CoreFoundation/CFString.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Sources/MachOKitC/include/core_foundation.h, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
Handle `__DATA*.__cfstring` section
- https://developer.apple.com/documentation/corefoundation/cfstring-rfh
=> Support table  of `CFString`

Sources/MachOKit/Extension/Data+.swift, Sources/MachOKit/Extension/UnsafePointer+.swift, Sources/MachOKit/LoadCommand/LinkerOptionCommand.swift, Sources/MachOKit/LoadCommand/Model/Section.swift, Sources/MachOKit/MachOFile+Strings.swift, Sources/MachOKit/MachOFile.swift, Sources/MachOKit/MachOImage+Strings.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Sources/MachOKit/Protocol/StringTable.swift, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
Handle __TEXT.__ustring section
=> Support table of UTF16 string

.github/workflows/update-prebuild-spm.yml
https://github.com/p-x9/MachOKit-SPM
- https://github.com/p-x9/MachOKit-SPM/pull/2
=> Add GitHub Actions workflow to update prebuilt SPM on release

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/Extension/dyld_chained_ptr+.swift, Sources/MachOKit/LoadCommand/LoadCommand.swift, Sources/MachOKit/LoadCommand/LoadCommandType.swift, Sources/MachOKit/LoadCommand/Model/Platform.swift, Sources/MachOKit/LoadCommand/TargetTripleCommand.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointer.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerContent.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerFormat.swift, Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerInfo.swift, Sources/MachOKit/Protocol/LoadCommandWrapper.swift, Sources/MachOKitC/include/backports.h, Sources/MachOKitC/include/fixup-chains.h, Sources/MachOKitC/mach-o/loader.h
New load commands:
- LC_FUNCTION_VARIANTS
- LC_FUNCTION_VARIANT_FIXUPS
- LC_TARGET_TRIPLE
=> Support new mach-o format from iOS 18.4 beta

Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointer.swift
=> Fix undefined symbol error (dyld_chained_ptr_arm64e_segmented_rebase)

Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoaderSet.swift
=> Support new prebuild loader format version from `dyld-1241.17`

.github/workflows/update-prebuild-spm.yml
- https://github.com/p-x9/MachOKit/actions/runs/14656865176
=> Fix acquisition of release information when updating prebuild spm.

Sources/MachOKit/MachOImage+Strings.swift
=> Fix 32-bit overflow issue in string table endianness detection

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/DyldCacheLoaded.swift, Sources/MachOKit/Model/DyldCache/DyldCacheFunctionVariantEntry.swift, Sources/MachOKit/Model/DyldCache/DyldCacheFunctionVariantInfo.swift, Sources/MachOKit/Model/DyldCache/DyldCachePrewarming.swift, Sources/MachOKit/Model/DyldCache/DyldCachePrewarmingEntry.swift, Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoaderSet.swift, Sources/MachOKit/Protocol/DyldCacheRepresentable.swift, Sources/MachOKitC/include/dyld_cache_format.h, Sources/MachOKitC/include/dyld_cache_loader.h, Tests/MachOKitTests/DyldCacheLoadedPrintTests.swift, Tests/MachOKitTests/DyldCachePrintTests.swift
- https://github.com/apple-oss-distributions/dyld/releases/tag/dyld-1284.13
- https://github.com/apple-oss-distributions/dyld/blob/031f1c6ffb240a094f3f2f85f20dfd9e3f15b664/include/mach-o/dyld_cache_format.h
=> Update dyld cache format (dyld-1284.13)

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/Extension/_FileIOProtocol+.swift, Sources/MachOKit/MachOFile+CodeSign.swift, Sources/MachOKit/MachOFile+DyldChainedFixups.swift, Sources/MachOKit/MachOFile+Strings.swift, Sources/MachOKit/MachOFile+Symbols.swift, Sources/MachOKit/MachOFile.swift
related: https://github.com/p-x9/MachOKit-SPM/issues/3
=> Use FileIO for file reading only for implementation.

Sources/MachOKit/DyldCache.swift, Sources/MachOKit/DyldCacheLoaded.swift, Sources/MachOKit/Model/DyldCache/DyldCachePrewarming.swift, Tests/MachOKitTests/DyldCachePrintTests.swift
There was a problem when parsing `iPhone17,1_18.4.1_22E252` prewarming data
=> Fix file offset calculation of tproMappings and prewarmingData

Sources/MachOKit/MachOFile.swift, Sources/MachOKit/MachOImage.swift, Sources/MachOKit/Protocol/MachORepresentable.swift, Tests/MachOKitTests/MachOFilePrintTests.swift, Tests/MachOKitTests/MachOPrintTests.swift
=> Add property to get `info.plist` embedded in `__TEXT,__info_plist`

Sources/MachOKit/FullDyldCache+host.swift
=> Add `host` property to FullDyldCache for macOS

Sources/MachOKit/DyldCache.swift
```swift
let cache: DyldCache
let mainCache = cache.mainCache
let fullCache = cache.fullCache
```
=> Add a convenience property to get full dyld cache from dyld cache
