- Sources/MachOKit/MachO+Symbols.swift
UInt -> Int
If the values are cast from unsigned to signed in a grouping, the values will be misaligned.
> fix numeric cast when calculating fileslide in symbols iter

- Sources/MachOKit/Extension/String+.swift
When the number of characters is the same as the size of the tuple, the null terminator is not included.
> Fixed Tuple to String conversion

- Sources/MachOKit/MachOImage+static.swift
- Sources/MachOKit/MachOImage.swift
- Sources/MachOKit/Protocol/MachORepresentable.swift
`dladdr` function excludes local symbols from the search
https://github.com/apple-oss-distributions/Libwrappers/blob/main/dlcompat/dlfcn.c#L1145
> Add option to search only global symbols

- Sources/MachOKit/Util/exported.swift
MachOKit imports exported MachO modules.
In this case, DocC also displays the symbols defined in the MachO module.
The following attributes are used to display only the symbols defined in MachOKit.
https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_documentationvisibility-
> Hide exported module's symbols from docc

- Tests/MachOKitTests/MachOPrintTests.swift
For all symbols, searching for the closest symbol would take a considerable amount of time.
> Omit part of test for closest symbols

- Sources/MachOKit/LoadCommand/Model/Section.swift
- Sources/MachOKit/LoadCommand/SegmentCommand.swift
There were properties between SegmentCommand and SegmentCommand64, and Section and Section64 that were common but not added to the protocol.
> Add some properties to Segment/Section protocol

- Sources/MachOKit/MachOFile.swift
Add a flag to check if the machO file is loaded from the dyld cache.
When this value is true, `url` indicates the path of the dyld cache file
> Add a flag to check if the machO file is loaded from the dyld cache

- Sources/MachOKit/DyldCache.swift
- Sources/MachOKit/Extension/Sequence+.swift
- Sources/MachOKit/Model/DyldCache/Loader/LoaderRef.swift
- Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoader.swift
- Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoaderSet.swift
- Sources/MachOKit/Model/DyldCache/ProgramOffset.swift
- Sources/MachOKit/Model/DyldCache/ProgramsTrieNodeContent.swift
- Sources/MachOKitC/include/dyld_cache_loader.h
- Tests/MachOKitTests/DyldCachePrintTests.swift
```c
uint64_t    programsPBLSetPoolAddr;     // (unslid) address of pool of PrebuiltLoaderSet for each program
uint64_t    programsPBLSetPoolSize;     // size of pool of PrebuiltLoaderSet for each program
uint64_t    programTrieAddr;            // (unslid) address of trie mapping program path to PrebuiltLoaderSet
uint32_t    programTrieSize;
```
> Support programs trie in dyld cache

- Sources/MachOKit/DyldCache+SubCaches.swift
- Sources/MachOKit/DyldCache.swift
- Sources/MachOKit/Model/DyldCache/DyldSubCacheEntry.swift
- Tests/MachOKitTests/DyldCachePrintTests.swift
A dyld cache may be split into several files and is obtained as a sub subcache of the main cache.
(Retrieval of the sub cache model is already implemented and can be obtained from the `subCaches` property.)
There were cases where some properties in the dyld cache header existed only in the main cache and the file offset indicated by the property existed in the sub cache.
Fixes have been made to ensure correct loading.
> Dyld Sub Cache loading

- Sources/MachOKit/DyldCache.swift
- Sources/MachOKit/MachOFile.swift
- Sources/MachOKit/Model/DyldCache/DyldCacheMappingAndSlideInfo.swift
- Sources/MachOKit/Model/DyldCache/SlideInfo/DyldCacheSlideInfo.swift
- Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointer.swift
- Sources/MachOKit/Model/DyldChain/DyldChainedFixupPointerContent.swift
When retrieving information from a mach-o file, there are cases where it is necessary to resolve the rebase and then retrieve the offset.
(For example, superclass or isa of objc class)
https://github.com/apple-oss-distributions/dyld/blob/d552c40cd1de105f0ec95008e0e0c0972de43456/common/MetadataVisitor.cpp#L262
> Resolve rebase / bind

- Sources/MachOKit/DyldCache.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderOptimizationRO.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/OldObjCOptimization.swift
- Sources/MachOKitC/include/objc.h
Old ObjC Optimisation exists in /usr/lib/libobjc.A.dylib in the __TEXT.__objc_opt_ro section
> Support old objc optimization

- Sources/MachOKitC/include/dyld_cache_format.h
`uuid/uuid.h` is available by default in apple platfom.
On the other hand, on Ubuntu and other linux platforms, it must be installed using the following command.
```sh
apt-get uuid-dev
```
However, as there is only one point of use, it has been modified to use the `uuid_t` defined by itself using `typedef`.
> Fix not to use `uuid/uuid.h`

- Package.swift
- Sources/MachOKit/Model/Codesign/CodeDirectory/CodeSignCodeDirectory.swift
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md
> Use access level instead of `(at)_implementationOnly`

- Sources/MachOKit/DyldCache.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderInfoRO.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderOptimizationRO.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCHeaderOptimizationRW.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/ObjCOptimization.swift
- Sources/MachOKit/Model/DyldCache/ObjCOptimization/OldObjCOptimization.swift
- Sources/MachOKitC/include/objc.h
- Tests/MachOKitTests/DyldCacheLoadedPrintTests.swift
- Tests/MachOKitTests/DyldCachePrintTests.swift
File and address offsets from the beginning of the main cache do not always match.
> [ObjC] Fix offset calculation in objc optimization

- Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoader.swift
- Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoaderProtocol.swift
- Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoaderSet.swift
- Sources/MachOKit/Model/DyldCache/Loader/PrebuiltLoader_Pre1165_3.swift
- Sources/MachOKitC/include/dyld_cache_loader.h
- Tests/MachOKitTests/DyldCacheLoadedPrintTests.swift
- Tests/MachOKitTests/DyldCachePrintTests.swift
| dyld version | macOS  | Version Hash    |
|--------------|--------|---------------------|
| dyld-940     | 12.0.1 | 68946390 (941.2.1)     |
| dyld-955     | 12.3.0 | 3414927712 (1041.6.0) |
| dyld-1042.1  | 13.2   | 1294698055 (1042.1.0) |
| dyld-1066    | 13.5   | 1294698055 (1066.8.0) |
| dyld-1122.1  | 14.1   | 3594994239 (1122.1.2) |
| dyld-1160.6  | 14.4   | 2590380128 (1160.6.0) |
| dyld-1165.3  | 14.6   | 2590380128 (1165.3.0) |
| dyld-1231.3  | 15.0   | 389703534 (1231.3.0) |
> [dyld cache] Support latest and older version of prebuilt loader

- Sources/MachOKit/Extension/Sequence+.swift
- Sources/MachOKit/MachOImage+static.swift
- Sources/MachOKit/MachOImage.swift
- Sources/MachOKit/Protocol/MachORepresentable.swift
- Tests/MachOKitTests/MachOFilePrintTests.swift
- Tests/MachOKitTests/MachOPrintTests.swift
In some cases, there may be more than one symbol in the Symbol table with the same name or offset.
> Fix to find multiple symbols with the same name/offset

- Sources/MachOKit/LoadCommand/DylibCommand.swift
- Sources/MachOKit/LoadCommand/DylibUseCommand.swift
- Sources/MachOKit/LoadCommand/Model/Dylib.swift
- Sources/MachOKit/LoadCommand/Model/DylibUseFlags.swift
- Sources/MachOKit/MachOFile.swift
- Sources/MachOKit/MachOImage.swift
- Sources/MachOKit/Model/DependedDylib.swift
- Tests/MachOKitTests/MachOFilePrintTests.swift
- Tests/MachOKitTests/MachOPrintTests.swift
> Support `dylib_use_command` introduced from macOS 15, iOS 18

- .github/workflows/release.yml
- #153
- #156
The pre-built binary is not backward compatible, so if you build with Xcode16, it will not be available for Xcode15 or earlier environments.
> Use Xcode15 for building xcframework in Github Action

- Sources/MachOKit/MachOFile.swift
- Sources/MachOKit/Model/CoreFoundation/CFString.swift
Binaries supporting platforms prior to macOS12 may use absolute addresses for vmaddr.
In such a case, you need to add a process to convert it to file offset.
We have implemented a function to convert to file offset, taking into account the tagged pointer of PAC and objc, and the range of valid vmaddr.
> Convert raw vmaddr to file offset

- Sources/MachOKit/Extension/TrieTreeProtocol+.swift
- Sources/MachOKit/MachOFile+ExportTrie.swift
- Sources/MachOKit/MachOImage+ExportTrie.swift
- Sources/MachOKit/Util/TrieTree/Model/TrieNode.swift
- Sources/MachOKit/Util/TrieTree/Protocol/TrieTreeProtocol.swift
- Tests/MachOKitTests/DyldCacheLoadedPrintTests.swift
- Tests/MachOKitTests/DyldCachePrintTests.swift
- Tests/MachOKitTests/MachOFilePrintTests.swift
- Tests/MachOKitTests/MachOPrintTests.swift
```swift
guard let exportTrie = machO.exportTrie else { return }
let prefix = "_$s"
let swiftSymbols = exportTrie.search(byKeyPrefix: prefix)
```
> Add methods to search in trie tree with key prefix

- Sources/MachOKit/LoadCommand/SegmentCommand.swift
- Sources/MachOKit/MachOImage+static.swift
- Sources/MachOKit/MachOImage.swift
- Sources/MachOKit/Protocol/MachORepresentable.swift
Not all segments, such as mach-o in the dyld cache, are located in contiguous memory space.
In the previous logic, a segment was considered to be included if it was larger than the address of the first segment and smaller than the address of the end of the last segment.
However, this was a mistake.
> Add method to check if specified address is contained in mach-o

- Sources/MachOKit/Header/CPU.swift
- Sources/MachOKit/Header/CPUSubType.swift
- Sources/MachOKit/Header/CPUType.swift
I've recently been writing a CLI for `MachOSwiftSection`, and I think `current` is a very convenient property, but I don't know why it's not exposed. If there are other reasons, please let me know, and I will close the PR.
> Make `current` property of CPU type as public and `CPU`, `CPUType`, `CPUSubType` types conform Equatable

- Sources/MachOKit/MachOImage.swift
`dladdr` function was used to implement this function, but it has been changed to use the load command.
> Refactor `path` property not to use `Darwin` function

- Sources/MachOKit/Protocol/_DyldCacheFileRepresentable.swift
`section.offset` is file offset.
For mach-o files within a subcache, this represents the offset within that subcache file.
> Fix offset calculation in OldObjCOptimization layout retrieval
